<a href="https://colab.research.google.com/github/student-Nit/Scientific-paper-title-generator/blob/main/Scientific_paper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers datasets beautifulsoup4 requests torch accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.3)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.9.0+cpu)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.11.12)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
!ls /content/drive/MyDrive

 10thmarksheet_2206298_GarimaVijay_CSE.pdf
 12thmarksheet_2206298_GarimaVijay_CSE.pdf
'12th marksheet.pdf'
 20230429_215207.PDF
 20240112_212240.jpg
 20240112_212415.jpg
'2206298 (1).pdf'
 2206298DL
 2206298_DM
 2206298DM.docx
'2206298_GarimaVijay_CSE_DataAnalyst (1).pdf'
'2206298_GarimaVijay_CSE_DataAnalyst (2).pdf'
'2206298_GarimaVijay_CSE_DataAnalyst (3).pdf'
'2206298_GarimaVijay_CSE_DataAnalyst (4).pdf'
 2206298_GarimaVijay_CSE_DataAnalyst.pdf
 2206298_GarimaVijay_Documents
 2206298.pdf
 319750232_1533043953825296_3127640811629933575_n.jpg
 42ad5d3e-b949-41aa-9a51-7dcac7fa3853.jpg
'AadharCard_2206298_GarimaVijay_CSE (3).pdf'
 AadharCard_2206298_GarimaVijay_CSE.pdf
'Applied_cryptography (2).pdf'
'back side.jpeg'
 BTechmarksheet_2206298_GarimaVijay_CSE.pdf
'B.TECH Marksheet_2206298.pdf'
 Chat-Application.tar
 Classroom
'Colab Notebooks'
'Copy of 2206298DM.docx'
'Copy of res.pdf'
 DOC-20250817-WA0057..pdf
 documentation.gdoc
'Document from G (1).pdf'
'Document from Garima (1).pdf'
'Document from Garima (2).pdf'
'Document from Garima.pdf'
'Document from GarimaVijay_2206298'
'Document from GarimaVijay_2206298 (10).pdf'
'Document from GarimaVijay_2206298 (11).pdf'
'Document from GarimaVijay_2206298 (12).pdf'
'Document from GarimaVijay_2206298 (13).pdf'
'Document from GarimaVijay_2206298 (14).pdf'
'Document from GarimaVijay_2206298 (1).pdf'
'Document from GarimaVijay_2206298 (2).pdf'
'Document from GarimaVijay_2206298 (3).pdf'
'Document from GarimaVijay_2206298 (4).pdf'
'Document from GarimaVijay_2206298 (5).pdf'
'Document from GarimaVijay_2206298 (6).pdf'
'Document from GarimaVijay_2206298 (7).pdf'
'Document from GarimaVijay_2206298 (8).pdf'
'Document from GarimaVijay_2206298 (9).pdf'
'Document from GarimaVijay_2206298.pdf'
'Document from G.pdf'
'Ethical hacking (1).pdf'
'Ethical hacking.pdf'
 Fast-Dreambooth
 feedback.mp4
'front side.jpeg'
 Garima.pdf
'garima Photo.jpeg'
 Garima_Res.pdf.pdf
"Garima's_Resume.pdf"
 GarimaVijay_2206298.pdf
'GarimaVijay_Application_form (2).pdf'
 GarimaVijay_Application_Form.pdf
'GarimaVijay_Resume (1).pdf'
 Garima_vijay_Resume.pdf
 GarimaVijay_Resume.pdf
 garim.jpg
'Industrial (2).pdf'
 merged_metr_la_with_weather.csv
 metrla_fin_normalized.csv
 metrla_fin_normalized.h5
 metr-la.h5
'metr-la_merged_with_weather (1).csv'
 metr-la_merged_with_weather.csv
 metr-la_weather_6hr.csv
 metr-la_weather_hourly.csv
 metr-la_weather_hourly_dailyfetch.csv
 MINOR.pptx
 NOc.pdf
 normalized-metr-la.h5
 normalized_metr_la_with_weather.h5
 normalized_metr_la_with_weather_v2.h5
 PANCard_220629_GarimaVijay_CSE.pdf
 pdf_converter_202210313136.pdf
 pems-bay.h5
'Project (1).pdf'
 project.mp4
'QFIX-PAYMENT-RECEIPT-Library Fee.pdf'
're (1).pdf'
 re.pdf
'res (1).pdf'
'res (2).pdf'
 res.pdf
 Resume
'Resume (1).pdf'
'Resume_2206298_GarimaVijay_CSE (1).pdf'
'Resume_2206298_GarimaVijay_CSE (2).pdf'
'Resume_2206298_GarimaVijay_CSE (3).pdf'
 Resume_2206298_GarimaVijay_CSE.pdf
'Resume (2).pdf'
'Resume (3) (1).pdf'
'Resume (3).pdf'
'Resume (4).pdf'
'Resume (5) (1).pdf'
'Resume (5).pdf'
'Resume (6).pdf'
'Resume (7).pdf'
'ResumeGarimaVijay (1).pdf'
'Resume_GarimaVijay_NITPATNA (1).pdf'
 Resume_GarimaVijay_NITPATNA.pdf
 Resume_GarimaVijay.pdf
 ResumeGarimaVijay.pdf
 Resume.pdf
 Screenshot_20231204-050013_PhonePe.jpg
 Screenshot_20240403-003217_PhonePe.jpg
 Screenshot_20250103_210158_PhonePe.jpg
 Screenshot_20250206_142537_PhonePe.jpg
'Screenshot 2025-10-18 074311.png'
'sem result.pdf'
 Transcript_2206298_GarimaVijay_CSE-page-001.jpg
 Transcript_2206298_GarimaVijay_CSE.pdf
 UNIT-II.gdoc
'Untitled form (1).gform'
'Untitled form (2).gform'
'Untitled form.gform'
'Untitled form (Responses).gsheet'
'User Guide.pdf'
'Water Level Indicator.pdf'
'WhatsApp Image 2023-08-31 at 22.35.12.jpeg'

In [8]:
!ls "/content/drive/MyDrive/Colab Notebooks"

 amazonml.ipynb
'Another copy of Untitled6.ipynb'
'Copy of Build your own GenAI Model [NxtWave Hands-On].ipynb'
'Copy of Untitled29.ipynb'
'Copy of Untitled33.ipynb'
'Copy of Untitled6 (1).ipynb'
'Copy of Untitled6.ipynb'
 CP_progress_tracker.ipynb
'Creditcard fraud detection.ipynb'
 kmeans.ipynb
 Lab1.ipynb
 Scientific-paper.ipynb
 Untitled
 Untitled0.ipynb
 Untitled10.ipynb
 Untitled11.ipynb
 Untitled12.ipynb
 Untitled13.ipynb
 Untitled14.ipynb
 Untitled15.ipynb
 Untitled16.ipynb
 Untitled17.ipynb
 Untitled18.ipynb
 Untitled19.ipynb
 Untitled1.ipynb
 Untitled20.ipynb
 Untitled21.ipynb
 Untitled22.ipynb
 Untitled23.ipynb
 Untitled24.ipynb
 Untitled25.ipynb
 Untitled26.ipynb
 Untitled27.ipynb
 Untitled28.ipynb
 Untitled29.ipynb
 Untitled2.ipynb
 Untitled30.ipynb
 Untitled31.ipynb
 Untitled32.ipynb
 Untitled33.ipynb
 Untitled34.ipynb
 Untitled35.ipynb
 Untitled3.ipynb
 Untitled4.ipynb
 Untitled5.ipynb
 Untitled6.ipynb
 Untitled7.ipynb
 Untitled8.ipynb
 Untitled9.ipynb

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

titles = []

for page in range(0, 20):
    url = f"https://arxiv.org/list/cs.AI/pastweek?skip={page*100}&show=100"
    html = requests.get(url).text
    soup = BeautifulSoup(html, 'html.parser')

    for tag in soup.find_all("div", class_="list-title"):
        title = tag.text.replace("Title:", "").strip()
        titles.append(title)

df = pd.DataFrame({"title": titles})
df.to_csv("arxiv_titles.csv", index=False)

print("Total Titles:", len(titles))
df.head()

Total Titles: 863

                                               title
0  Agent Drift: Quantifying Behavioral Degradatio...
1  ComfySearch: Autonomous Exploration and Reason...
2  MobileDreamer: Generative Sketch World Model f...
3  Anti-Length Shift: Dynamic Outlier Truncation ...
4  Trade-R1: Bridging Verifiable Rewards to Stoch...

In [ ]:
df = pd.read_csv("arxiv_titles.csv")
df["title"] = df["title"].str.lower()
df["title"] = df["title"].str.replace(r"[^a-zA-Z0-9 ]","", regex=True)

with open("train.txt","w",encoding="utf-8") as f:
    for t in df["title"]:
        f.write(t + "\n")

print("Training file ready!")

Training file ready!

In [ ]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel, TextDataset, DataCollatorForLanguageModeling

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token

dataset = TextDataset(
    tokenizer=tokenizer,
    file_path="train.txt",
    block_size=64
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

model = GPT2LMHeadModel.from_pretrained("gpt2")

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/data/datasets/language_modeling.py:53: FutureWarning: This dataset will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py
  warnings.warn(

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./title_generator",
    overwrite_output_dir=True,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    save_steps=500,
    logging_steps=100,
    fp16=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=dataset
)

trainer.train()

model.save_pretrained("title_generator")
tokenizer.save_pretrained("title_generator")

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 4

wandb: WARNING Invalid choice
wandb: Enter your choice:

 2

wandb: You chose 'Use an existing W&B account'
wandb: Logging into https://api.wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: Find your API key here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: vijaygarima18 (vijaygarima18-national-institute-of-technology-patna) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

('title_generator/tokenizer_config.json',
 'title_generator/special_tokens_map.json',
 'title_generator/vocab.json',
 'title_generator/merges.txt',
 'title_generator/added_tokens.json')

In [ ]:
import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("title_generator")
model = GPT2LMHeadModel.from_pretrained("title_generator")


tokenizer.add_special_tokens({'pad_token': '[PAD]'})
model.resize_token_embeddings(len(tokenizer))

def generate_title(prompt):
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        padding=True,
        truncation=True
    )

    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]

    outputs = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_length=15,
        num_return_sequences=1,
        do_sample=True,
        top_k=50,
        top_p=0.95
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

print(generate_title("graph neural networks"))
print(generate_title("deep learning for healthcare"))

The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

graph neural networks with machine learning and semantic reasoning
deep convolutional networks
deep learning for healthcare coordination in remote collaboration environments
infrared vision and spectral

In [9]:
import json

nb_file = "/content/drive/MyDrive/Colab Notebooks/Scientific-paper.ipynb"

with open(nb_file, "r", encoding="utf-8") as f:
    nb = json.load(f)

if "widgets" in nb.get("metadata", {}):
    del nb["metadata"]["widgets"]

fixed_file = "/content/drive/MyDrive/Colab Notebooks/Scientific-paper-fixed.ipynb"

with open(fixed_file, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=2)

print("Notebook fixed successfully!")

Notebook fixed successfully!